ngnix-image:
 image: nginx:latest
 ports:
  - "80:80"
 volumes:
  - /var/lib/jenkins/workspace/php-ci-cd/:/phpprojects/project1/
  - /var/lib/jenkins/workspace/php-ci-cd/site1.conf:/etc/nginx/conf.d/site1.conf

php-image:
 image: php:7-fpm
 volumes:
  - /var/lib/jenkins/workspace/php-ci-cd/:/phpprojects/
