ngnix-image:
 container_name: nginx
 image: nginx:latest
 ports:
  - "80:80"
 volumes:
  - /var/lib/jenkins/workspace/php-ci-cd:/phpprojects
  - /var/lib/jenkins/workspace/php-ci-cd/default.conf:/etc/nginx/conf.d/default.conf

 links:
   - php-image


php-image:
 container_name: php
 image: php:7-fpm
 volumes:
  - /var/lib/jenkins/workspace/php-ci-cd/:/phpprojects
