ngnix-image:
 image: nginx:latest
 ports:
  - "8050:80"
 volumes:
  - /var/lib/jenkins/workspace/php-ci-cd/:/var/lib/jenkins/workspace/php-ci-cd
  - /var/lib/jenkins/workspace/php-ci-cd/site1.conf:/etc/nginx/conf.d/default.conf

 links:
   - php-image


php-image:
 image: php:7-fpm
 volumes:
  - /var/lib/jenkins/workspace/php-ci-cd/:/phpprojects/
